[package]
name = "foux"
edition = "2021"
version = "0.0.2"
license = "GPL"
author = "DhavySantos"
license-path = "license"
description = "Foux Game Engine"

[dependencies]
cgmath = "0.18.0"
glfw = "0.58.0"
gl = "0.14.0"
