[package]
name = "foux"
edition = "2021"
version = "0.0.333"
license = "GPL-3.0"
author = "DhavySantos"
description = "Foux Game Engine"

[dependencies]
glfw = "0.58.0"
gl = "0.14.0"
nalgebra-glm = "0.19.0"
